### ISSUE TITLE
tiny suggestion: node modules 

### ISSUE THREAD

**Issue by Blazing-Mike** [elizabeth-jane/my-bot#1]
Hey there,

I think you might have committed your node_modules to GitHub which isn't really a great practice.

You can create a `.gitignore` file in your project root and add `node_modules/` and any other file/folder name you don't want to commit to GitHub.

**Comment by elizabeth-jane** [comment]
thank you so much i'll fix that right away

**Comment by elizabeth-jane** [comment]
> Hey there,
> 
> I think you might have committed your node_modules to GitHub which isn't really a great practice.
> 
> You can create a `.gitignore` file in your project root and add `node_modules/` and any other file/folder name you don't want to commit to GitHub.

> thank you so much i'll fix that right away

**Comment by Blazing-Mike** [comment]
you're welcome.
